# I think it's hilarious this is written in perl,
# and I won't change it.
# This will create out ~/.bashrc file
use strict;
use warnings;

open(my $fd, ">/root/.bashrc") or die "Couldn't open: $!";

print $fd("\n# Go\n");
print $fd("\nexport GOROOT=/src\n");
print $fd("\nexport GOPATH=/src/go\n");
print $fd("\nexport GOBIN=/src/go/bin\n");

print $fd("\n# Autogenerated Aliases\n");
print $fd("alias c=\"clear\"\n");
print $fd("alias src=\"cd /src\"\n");
print $fd("alias art=\"cd /src/art\"\n");
print $fd("alias python=\"python3\"\n");
print $fd("alias py=\"python\"\n");

# Writes our bash ps1
print $fd("\n\n# PS1\n");
print $fd('if [ "`id -u`" -eq 0 ]; then
    PS1="\[\033[m\]|\[\033[1;35m\]\t\[\033[m\]|\[\e[1;31m\]\u\[\e[1;36m\]\[\033[m\]@\[\e[1;36m\]\h\[\033[m\]:\[\e[0m\]\[\e[1;32m\][\W]> \[\e[0m\]"
else
    PS1="\[\033[m\]|\[\033[1;35m\]\t\[\033[m\]|\[\e[1m\]\u\[\e[1;36m\]\[\033[m\]@\[\e[1;36m\]\h\[\033[m\]:\[\e[0m\]\[\e[1;32m\][\W]> \[\e[0m\]"
fi
');
