use strict;
use warnings;

open(my $fd, ">>/root/.bashrc") or die "Couldn't open: $!";

print $fd("\n\n# Autogenerated Aliases\n");
print $fd("alias c=\"clear\"\n");
print $fd("alias src=\"cd /src\"\n");
print $fd("alias python=\"python3\"\n");
print $fd("alias py=\"python\"\n");
